theme: jekyll-theme-minimal
title: Elan Berezovskiy's Website
description: In progress on creating a website

defaults:
  -
    scope:
      path: ""
    values:
      theme: jekyll-theme-minimal
      author: "Elan Berezovskiy"
